<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-7K788E1M" failures="8" tests="44" name="com.CA.qa.TestCases.ValidateCampaignPageTest" time="213.088" errors="0" timestamp="2020-08-25T18:51:33 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameErrorMsg" time="0.180"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameRangeErrorMsg" time="0.251">
    <failure message="expected [Campaign Name should be between 2 to 255 characters.] but found [Campaign Name should be between 2 to 255 alphanumeric characters long and allows special characters like .,@,_,-]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Campaign Name should be between 2 to 255 characters.] but found [Campaign Name should be between 2 to 255 alphanumeric characters long and allows special characters like .,@,_,-]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateCampaignNameRangeErrorMsg(ValidateCampaignPageTest.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateCampaignNameRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg" time="0.226"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignTypeErrorMsg" time="0.148"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidErrorMsg" time="0.135"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidRangeErrorMsg" time="0.221"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidRangeMaxErrorMsg" time="0.271"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateStartTimeErrorMsg" time="0.147"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateEndTimeErrorMsg" time="0.135"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateGreaterEndTimeErrorMsg" time="0.391"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePriorityErrorMsg" time="0.127"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePriorityRangeErrorMsg" time="0.268"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePluginNameErrorMsg" time="0.309"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesErrorMsg" time="0.131"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesRangeErrorMsg" time="0.257"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesRangemaxErrorMsg" time="0.242"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateWrapupErrorMsg" time="10.122">
    <failure message="expected [Wrapup Time (in Sec) is required.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Wrapup Time (in Sec) is required.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateWrapupErrorMsg(ValidateCampaignPageTest.java:223)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateWrapupErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDispositionErrorMsg" time="0.155"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateSkillErrorMsg" time="0.138"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapErrorMsg" time="10.131">
    <failure message="expected [Mapping Name is required.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Mapping Name is required.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateMapErrorMsg(ValidateCampaignPageTest.java:247)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateUploadErrorMsg" time="10.131">
    <failure message="expected [File to Upload is required.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [File to Upload is required.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateUploadErrorMsg(ValidateCampaignPageTest.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateUploadErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDialIntervalErrorMsg" time="0.383"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateAppUrlEmptyErrorMsg" time="0.259"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateAppUrlInvalidErrorMsg" time="0.395"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsEmptyErrorMsg" time="0.259"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsRangeErrorMsg" time="0.387"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsMaxRangeErrorMsg" time="0.385"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeEmptyErrorMsg" time="13.345">
    <failure message="expected [Customer Ringing Time is required.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Customer Ringing Time is required.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateCustomerRingTimeEmptyErrorMsg(ValidateCampaignPageTest.java:321)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateCustomerRingTimeEmptyErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeRangeErrorMsg" time="10.443">
    <failure message="expected [Customer Ringing Time should be between 1 and 60.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Customer Ringing Time should be between 1 and 60.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateCustomerRingTimeRangeErrorMsg(ValidateCampaignPageTest.java:331)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateCustomerRingTimeRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeRangeMaxErrorMsg" time="10.412">
    <failure message="expected [Customer Ringing Time should be between 1 and 60.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Customer Ringing Time should be between 1 and 60.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateCustomerRingTimeRangeMaxErrorMsg(ValidateCampaignPageTest.java:341)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateCustomerRingTimeRangeMaxErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePacingRatioEmptyErrorMsg" time="3.473"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg" time="0.344"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMaxDropRatioEmptyErrorMsg" time="0.247"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMaxDropRatioRangeErrorMsg" time="0.335"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateEmptyMapNameErrorMsg" time="21.386"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapNameRangeErrorMsg" time="31.520">
    <failure message="expected [Map Name should be between 2 to 50 characters.] but found [Map Name allows alphanumeric characters with Underscore]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Map Name should be between 2 to 50 characters.] but found [Map Name allows alphanumeric characters with Underscore]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateMapNameRangeErrorMsg(ValidateCampaignPageTest.java:407)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapNameRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapNameSplRangeErrorMsg" time="31.448"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileErrorMsg" time="21.332"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileSampleTooltipMsg" time="11.209"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileXlsOnlyTooltipMsg" time="11.197"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateFileUploadSampleTooltipMsg" time="0.026"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateFileUploadXlsOnlyTooltipMsg" time="0.022"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMappingTooltipMsg" time="0.017"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConsolidatedErrMsg" time="10.148"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ValidateCampaignPageTest -->
