<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="4" tests="25" name="com.CA.qa.TestCases.ConfigurationPageTest" time="852.290" errors="0" timestamp="2021-07-26T19:01:40 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddPhoneNos" time="30.410"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddPhoneNos" time="26.803"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddPhoneNos" time="16.058">
    <failure message="Phone No 20102 not added expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Phone No 20102 not added expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.ConfigurationPageTest.AddPhoneNos(ConfigurationPageTest.java:194)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddPhoneNos -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddTransferNos" time="19.489">
    <failure message="Transfer no 9553578723  not able to edit expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Transfer no 9553578723  not able to edit expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.ConfigurationPageTest.AddTransferNos(ConfigurationPageTest.java:243)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddTransferNos -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddTransferNos" time="16.624"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddTransferNos" time="19.784">
    <failure message="9553578724 Phone No not able to delete expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 9553578724 Phone No not able to delete expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.ConfigurationPageTest.AddTransferNos(ConfigurationPageTest.java:250)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddTransferNos -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDispositions" time="15.783"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDispositions" time="20.823"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDispositions" time="31.159"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfDispositions" time="55.999"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDialoutNumbers" time="30.860"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDialoutNumbers" time="33.238"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDialoutNumbers" time="20.289"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddDialoutNumbers" time="16.967"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfDialout" time="75.680"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddpauseReasons" time="20.882"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddpauseReasons" time="21.503"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddpauseReasons" time="17.324"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="AddpauseReasons" time="20.295"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfPauseReasons" time="76.972"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="BlockNumberBlocking_Unblocking" time="41.323"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfBlockNumber" time="65.741"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="Add_edit_delete_AgentGroup" time="14.480">
    <failure message=" Add header not matching expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  Add header not matching expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.ConfigurationPageTest.Add_edit_delete_AgentGroup(ConfigurationPageTest.java:632)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Add_edit_delete_AgentGroup -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfAgentGroup" time="76.798"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ConfigurationPageTest" name="ShowFunctionalityOfAgents" time="67.006"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ConfigurationPageTest -->
