<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="5" tests="25" name="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" time="28.438" errors="0" timestamp="2021-06-01T20:47:13 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateCampaignNameErrorMsg25_1" time="1.153"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateCampaignNameDuplicateErrorMsg25_11" time="1.192"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateCampaignNameRangeErrorMsg25_12" time="1.192"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg25_13" time="1.175"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg25_14" time="1.189"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidErrorMsg25_2" time="1.127"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidRangeErrorMsg25_21" time="1.196">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateInboundCampaignPageTest.ValidateDidRangeErrorMsg25_21(ValidateInboundCampaignPageTest.java:153)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg25_21 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidRangeErrorMsg25_23" time="1.181">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateInboundCampaignPageTest.ValidateDidRangeErrorMsg25_23(ValidateInboundCampaignPageTest.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg25_23 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidDuplicateErrorMsg25_22" time="1.196"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidRangeErrorMsg25_24" time="1.167">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateInboundCampaignPageTest.ValidateDidRangeErrorMsg25_24(ValidateInboundCampaignPageTest.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg25_24 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidRangeErrorMsg25_25" time="1.171">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateInboundCampaignPageTest.ValidateDidRangeErrorMsg25_25(ValidateInboundCampaignPageTest.java:187)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg25_25 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDidRangeMaxErrorMsg" time="1.204">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateInboundCampaignPageTest.ValidateDidRangeMaxErrorMsg(ValidateInboundCampaignPageTest.java:195)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeMaxErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg25_3" time="1.212"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg25_31" time="1.186"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg25_32" time="1.183"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg25_33" time="1.198"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg25_4" time="1.250"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg25_41" time="1.231"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateBlockNoEmptyErrorMsg25_8" time="1.217"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg25_42" time="1.207"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateSkillErrorMsg25_5" time="1.111"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateWrapupErrorMsg25_6" time="1.108"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDispositionErrorMsg25_7" time="1.092"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidatePluginNameErrorMsg25_9" time="1.266"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateInboundCampaignPageTest" name="ValidateDefaultManualDialDisabledOrNot" time="0.034"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ValidateInboundCampaignPageTest -->
