<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="2" tests="17" name="com.CA.qa.TestCases.AdminHomePageTest" time="348.183" errors="0" timestamp="2021-07-26T14:52:51 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyAdminHomePage_TitleTest" time="12.186"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyclickingoninbound" time="22.682"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyclickingonOutbound" time="15.413"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyAdminLogout" time="15.952"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyOutboundAddCampaignButton" time="23.014"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyInboundAddCampaignButton" time="24.687"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifywhetherRunningInboundCampaignDIDEditable" time="23.908"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifywhetherRunningOutboundCampaignDIDEditable" time="21.031">
    <failure message="expected [not able to edit] but found [campaign not found or not running]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [not able to edit] but found [campaign not found or not running]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.AdminHomePageTest.verifywhetherRunningOutboundCampaignDIDEditable(AdminHomePageTest.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifywhetherRunningOutboundCampaignDIDEditable -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifywhetherRunningOutboundCampaignDeletable" time="19.970">
    <failure message="expected [delete is not available] but found [Campaign not Running]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [delete is not available] but found [Campaign not Running]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.AdminHomePageTest.verifywhetherRunningOutboundCampaignDeletable(AdminHomePageTest.java:149)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifywhetherRunningOutboundCampaignDeletable -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifywhetherRunningInboundCampaignDeletable" time="67.162"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyEditProfileIcon1_17" time="14.121"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyInBoundCampaignIcon1_17" time="14.019"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyoutBoundCampaignIcon1_17" time="16.075"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyAgentsIcon1_17" time="13.090"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyFwpNumberIcon1_17" time="13.816"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifySkillIcon1_17" time="17.472"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.AdminHomePageTest" name="verifyPauseReasonIcon1_17" time="13.585"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.AdminHomePageTest -->
